from .factions import Faction
from .races import Race

archetypes = {
    "Vault Dweller": {
        "race": Race.HUMAN,
        "skin_tone": "Fair",
        "body_type": "Athletic",
        "haircut": "Ponytail",
        "headgear": "None",
        "faction": Faction.VAULT_DWELLER,
        "outfit": "Blue Vault Suit",
        "weapon": "10mm Pistol",
        "object": "Pip-Boy (on left wrist)",
        "expression": "Determined",
        "pose": "Standing confidently",  # Using pose_options
        "background": "Vault Interior",  # Using background_options
    },
    "Brotherhood Knight": {
        "race": Race.HUMAN,
        "skin_tone": "Tan",
        "body_type": "Muscular",
        "haircut": "Military Cut",
        "headgear": "Brotherhood Hood",
        "faction": Faction.BROTHERHOOD_OF_STEEL,
        "outfit": "Power Armor T-51",
        "weapon": "Laser Rifle",
        "object": "Holotags (on chain)",
        "expression": "Heroic",
        "pose": "Power armor stance",
        "background": "Brotherhood Airship",
    },
    "Enclave Soldier": {
        "race": Race.HUMAN,
        "skin_tone": "Fair",
        "body_type": "Athletic",
        "haircut": "Military Cut",
        "headgear": "Enclave Helmet",
        "faction": Faction.ENCLAVE,
        "outfit": "Power Armor X-01",
        "weapon": "Plasma Rifle",
        "object": "Enclave Radio (on belt)",
        "expression": "Stoic",
        "pose": "Weapon drawn",  # Example pose
        "background": "Pre-War Suburb",
    },
    "Raider Warlord": {
        "race": Race.HUMAN,
        "skin_tone": "Tan",
        "body_type": "Muscular",
        "haircut": "Mohawk",
        "headgear": "Raider Cage Mask",
        "faction": Faction.RAIDERS,
        "outfit": "Spike Armor",
        "weapon": "Minigun",
        "object": "Bottlecap Pouch (on belt)",
        "expression": "Battle Cry",
        "pose": "Alert and wary",  # Example pose
        "background": "Wasteland Ruins",
    },
    "Super Mutant Brute": {
        "race": Race.SUPER_MUTANT,
        "skin_tone": "Green",
        "body_type": "Hulking",
        "haircut": "Bald",
        "headgear": "None",
        "faction": Faction.SUPER_MUTANT_TRIBE,
        "outfit": "Raider Leathers",
        "weapon": "Super Sledge",
        "object": "",
        "expression": "Angry",
        "pose": "Action shot",
        "background": "Super Mutant Camp",
    },
    "Institute Courser": {
        "race": Race.SYNTH,
        "skin_tone": "Synthetic Fair",
        "body_type": "Athletic",
        "haircut": "Clean Cut",
        "headgear": "None",
        "faction": Faction.THE_INSTITUTE,
        "outfit": "Institute Lab Coat",
        "weapon": "Institute Pistol",
        "object": "Synth Relay Chip (in hand)",
        "expression": "Cold Calculation",
        "pose": "Stealth crouch",
        "background": "The Institute",
    },
    "NCR Ranger": {
        "race": Race.HUMAN,
        "skin_tone": "Brown",
        "body_type": "Athletic",
        "haircut": "Short Hair",
        "headgear": "Ranger Helmet",
        "faction": Faction.NCR,
        "outfit": "Combat Armor",
        "weapon": ".44 Magnum",
        "object": "NCR Dogtag (displaying)",
        "expression": "Determined",
        "pose": "Weapon drawn",
        "background": "New Vegas Strip",
    },
    "Ghoul Mercenary": {
        "race": Race.GHOUL,
        "skin_tone": "Mottled",
        "body_type": "Wiry",
        "haircut": "Patchy Hair",
        "headgear": "Combat Helmet",
        "faction": Faction.NONE,
        "outfit": "Combat Armor",
        "weapon": "Combat Shotgun",
        "object": "Bottlecaps (counting)",
        "expression": "Suspicious",
        "pose": "Alert and wary",
        "background": "Nuclear Crater",
    },
    "Wasteland Survivor": {
        "race": Race.HUMAN,
        "skin_tone": "Weathered",
        "body_type": "Lean",
        "haircut": "Long Hair",
        "headgear": "Bandana",
        "faction": Faction.NONE,
        "outfit": "Leather Armor",
        "weapon": "Hunting Rifle",
        "object": "Water Canteen (on hip)",
        "expression": "Exhausted",
        "pose": "Scavenging through debris",
        "background": "Red Rocket Station",
    },
    "Caesar's Legionary": {
        "race": Race.HUMAN,
        "skin_tone": "Tan",
        "body_type": "Athletic",
        "haircut": "Short Hair",
        "headgear": "Legion Helmet",
        "faction": Faction.CAESARS_LEGION,
        "outfit": "Legion Armor",
        "weapon": "Machete",
        "object": "Legion Denarius (in palm)",
        "expression": "Disciplined",
        "pose": "Standing confidently",
        "background": "Wasteland Ruins",
    },
    "Children of Atom Zealot": {
        "race": Race.HUMAN,
        "skin_tone": "Radiation-Burned",
        "body_type": "Gaunt",
        "haircut": "Shaved Head",
        "headgear": "Gas Mask",
        "faction": Faction.CHILDREN_OF_ATOM,
        "outfit": "Rad-Soaked Robes",
        "weapon": "Gamma Gun",
        "object": "Glowing Vial (as pendant)",
        "pose": "Meditating/praying",
        "background": "Nuclear Crater",
    },
}
