pose_options = [
    "Standing confidently",
    "Combat ready",
    "Checking Pip-Boy",
    "Faction salute",
    "Alert and wary",
    "Action shot",
    "Crafting/Trading",
    "Stealth crouch",
    "Power armor stance",
    "Wounded but resilient",
    "Repairing equipment",
    "Weapon drawn",
    "Scavenging through debris",
    "Meditating/praying",
]

pose_emojis = {
    "Standing confidently": "💪",
    "Combat ready": "⚔️",
    "Checking Pip-Boy": "📟",
    "Faction salute": "👋",
    "Alert and wary": "👀",
    "Action shot": "💥",
    "Crafting/Trading": "🛠️",
    "Stealth crouch": "🥷",
    "Power armor stance": "🤖",
    "Wounded but resilient": "❤️‍🩹",
    "Repairing equipment": "🔧",
    "Weapon drawn": "🔫",
    "Scavenging through debris": "♻️",
    "Meditating/praying": "🙏",
}

background_options = [
    "Vault Interior",
    "Wasteland Ruins",
    "Brotherhood Airship",
    "Super Mutant Camp",
    "Nuclear Crater",
    "Pre-War Suburb",
    "Red Rocket Station",
    "Nuka-World",
    "Raider Outpost",
    "Settlement",
    "Abandoned Factory",
    "The Institute",
    "New Vegas Strip",
]
